#!/usr/bin/env bash
# Reading a `cf` (Cloudflare CLI) command line. Sourced by
# scripts/guard-cloudflare.sh.
#
# cf maps almost every command to one REST API request. lib/cf-commands.tsv,
# generated by scripts/gen-cf-table.py from cf's own manifest, records that
# request (method and path template), the positional arguments, which options
# take a value, and which carry a credential. The guard fills the path template
# from the command line and checks the result exactly like a curl call.

CF_TABLE="${CF_TABLE:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" 2>/dev/null && pwd -P)/cf-commands.tsv}"

# Global options of every cf command (from `cf <any> --help`). yargs accepts
# them anywhere, before the command path too.
CF_GLOBAL_VAL=" -z --zone --profile -m --mode --persist-to "
CF_GLOBAL_BOOL=" -q --quiet --local -h --help -v --version "

# cf_bool <word> <next word> — how yargs reads a boolean flag: sets CF_B to 1 or
# 0 and CF_BN to the words it takes. Bare or =true is true, and so is a
# following "true"; =anything else (0, 1, TRUE, no, empty) is false.
cf_bool() {
  CF_B=1; CF_BN=1
  if [[ "$1" == --no-* ]]; then CF_B=0
  elif [[ "$1" == *=* ]]; then [[ "${1#*=}" == true ]] || CF_B=0
  elif [[ "$2" == true || "$2" == false ]]; then
    [[ "$2" == true ]] || CF_B=0; CF_BN=2
  fi
}

# cf_lookup <path> — sets CF_ROW to the table line for an exact command path.
cf_lookup() {
  CF_ROW=$(CF_P="$1" awk -F '\t' '$1 == ENVIRON["CF_P"] { print; exit }' "$CF_TABLE" 2>/dev/null)
  [[ -n "$CF_ROW" ]]
}

# parse_cf — reads SH_WORDS from SH_START + 1. Sets:
#   CF_CMD CF_KIND CF_METHOD CF_API CF_CATEGORY   the command and its table row
#   CF_ARGN[] CF_ARGV[]       positional argument names and the values given
#   CF_OPTN[] CF_OPTV[]       options given (name without dashes, last value)
#   CF_ZONE CF_MODE CF_DRYRUN CF_HELP CF_BODY CF_DUP CF_SECRET_LIT CF_FIRSTPOS
#   CF_BADLEAD   an option before the command path that is not a global one
# CF_HELP and CF_DRYRUN are 1 only when every occurrence reads true: a mix is
# checked as a real run.
parse_cf() {
  CF_CMD=""; CF_KIND=""; CF_METHOD=""; CF_API=""; CF_CATEGORY=""; CF_ARGN=(); CF_ARGV=()
  CF_OPTN=(); CF_OPTV=(); CF_ZONE=""; CF_MODE=""; CF_DRYRUN=0; CF_HELP=0; CF_BODY=""; CF_DUP=""
  CF_SECRET_LIT=""; CF_FIRSTPOS=""; CF_BADLEAD=""
  local n=${#SH_WORDS[@]} j=$((SH_START + 1)) t f val b k p i help_seen=0 help_off=0 dry_seen=0 dry_off=0
  local -a lead=()
  # The command path: the leading words, skipping global options. Anything else
  # starting with - ends it; before the first word, cf would read the line
  # differently from the guard (an unknown option takes the next word as its
  # value, and -- ends option parsing), so it is refused.
  while (( j < n )); do
    t=${SH_WORDS[j]}; f=${t%%=*}
    if [[ "$t" != -- && "$CF_GLOBAL_VAL" == *" $f "* ]]; then
      [[ "$t" == *=* ]] && j=$((j + 1)) || j=$((j + 2)); continue
    fi
    if [[ "$t" != -- && "$CF_GLOBAL_BOOL" == *" $f "* ]]; then
      cf_bool "$t" "${SH_WORDS[j+1]:-}"; j=$((j + CF_BN)); continue
    fi
    if [[ "$t" == -* ]]; then (( ${#lead[@]} == 0 )) && CF_BADLEAD="$t"; break; fi
    lead[${#lead[@]}]="$t"
    j=$((j + 1))
  done
  CF_FIRSTPOS="${lead[0]:-}"
  k=${#lead[@]}; (( k > 5 )) && k=5
  while (( k > 0 )); do
    p="${lead[0]}"; i=1
    while (( i < k )); do p="$p ${lead[i]}"; i=$((i + 1)); done
    if cf_lookup "$p"; then CF_CMD="$p"; break; fi
    k=$((k - 1))
  done
  [[ -n "$CF_CMD" ]] || { CF_LEAD=$k; return 0; }
  local kind method api args vals secrets cat
  IFS=$'\t' read -r _ kind method api args vals secrets cat <<< "$CF_ROW"
  CF_KIND=$kind; CF_METHOD=$method; CF_API=$api; CF_CATEGORY=$cat
  local -a argn=()
  [[ "$args" == - ]] || IFS=, read -r -a argn <<< "$args"
  vals=",${vals},"; secrets=",${secrets},"

  # Everything after the command path, in order. After -- nothing is an option.
  local skip=$k pos=0 opts=1
  j=$((SH_START + 1))
  while (( j < n )); do
    t=${SH_WORDS[j]}
    if (( opts )) && [[ "$t" == -- ]]; then opts=0; j=$((j + 1)); continue; fi
    if (( opts )) && [[ "$t" == -?* ]]; then
      f=${t%%=*}
      val=""
      local name=${f#--}; name=${name#-}
      # Booleans the guard acts on, read the way yargs reads them.
      b=""
      case "$f" in
        -h|--help|--no-help|-v|--version|--no-version) b=help ;;
        --dry-run|--no-dry-run) b=dry ;;
      esac
      if [[ -n "$b" ]]; then
        cf_bool "$t" "${SH_WORDS[j+1]:-}"
        case "$b" in
          help) help_seen=1; (( CF_B )) || help_off=1 ;;
          dry)  dry_seen=1;  (( CF_B )) || dry_off=1 ;;
        esac
        j=$((j + CF_BN)); continue
      fi
      if [[ "$t" == *=* ]]; then val=${t#*=}
      elif [[ "$CF_GLOBAL_VAL" == *" $f "* || ( "$f" == --* && "$vals" == *",$name,"* ) ]]; then
        val="${SH_WORDS[j+1]:-}"; j=$((j + 1))
      else
        cf_bool "$t" "${SH_WORDS[j+1]:-}"           # a boolean option
        j=$((j + CF_BN)); continue
      fi
      case "$f" in
        -z|--zone) CF_ZONE="$val" ;;
        -m|--mode) CF_MODE="$val" ;;
        --body)    CF_BODY="$val" ;;
      esac
      # A literal credential, except a --body read from a file (@path).
      if [[ "$secrets" == *",$name,"* ]] && is_literal "$val" && [[ -z "$CF_SECRET_LIT" ]] &&
         ! [[ "$name" == body && "$val" == @?* ]]; then
        CF_SECRET_LIT="--$name"
      fi
      # An option given twice: the guard cannot know which value cf uses.
      for i in ${CF_OPTN[@]+"${!CF_OPTN[@]}"}; do
        [[ "${CF_OPTN[i]}" == "$name" && "${CF_OPTV[i]}" != "$val" ]] && CF_DUP="--$name"
      done
      CF_OPTN[${#CF_OPTN[@]}]="$name"; CF_OPTV[${#CF_OPTV[@]}]="$val"
      j=$((j + 1)); continue
    fi
    if (( skip > 0 )); then skip=$((skip - 1)); j=$((j + 1)); continue; fi
    CF_ARGN[${#CF_ARGN[@]}]="${argn[pos]:-extra}"; CF_ARGV[${#CF_ARGV[@]}]="$t"
    pos=$((pos + 1)); j=$((j + 1))
  done
  (( help_seen && ! help_off )) && CF_HELP=1
  (( dry_seen && ! dry_off )) && CF_DRYRUN=1
  return 0
}

# cf_opt <name> — sets CF_V to the option's value; fails when not given.
cf_opt() {
  local i
  CF_V=""
  for i in ${CF_OPTN[@]+"${!CF_OPTN[@]}"}; do
    [[ "${CF_OPTN[i]}" == "$1" ]] && { CF_V="${CF_OPTV[i]}"; return 0; }
  done
  return 1
}

# cf_param <path param> — sets CF_V to the value the command gives a path
# parameter: the positional or option of the same name (dashes for underscores),
# or a known alias (`workers deployments create --worker` names the script).
cf_param() {
  local p="$1" d i
  d=${p//_/-}
  CF_V=""
  for i in ${CF_ARGN[@]+"${!CF_ARGN[@]}"}; do
    [[ "${CF_ARGN[i]}" == "$d" || "${CF_ARGN[i]}" == "$p" ]] && { CF_V="${CF_ARGV[i]}"; return 0; }
  done
  cf_opt "$d" && return 0
  cf_opt "$p" && return 0
  case "$p" in
    script_name) cf_opt worker && return 0; cf_opt script && return 0 ;;
  esac
  return 1
}

# The name a create command gives the new resource, from its options. Sets CF_V
# and CF_NAME_OPT; fails when the command names it nowhere the guard can read.
CF_NAME_OPTS="name title queue-name bucket-name script-name database-name index-name project-name namespace-name tunnel-name"
cf_create_name() {
  local o
  CF_NAME_OPT=""
  for o in $CF_NAME_OPTS; do
    if cf_opt "$o"; then CF_NAME_OPT="--$o"; return 0; fi
  done
  return 1
}

# The nearest cloudflare.config.ts from a directory upward, or fail.
cf_config_ts() {
  local dir="$1"
  while :; do
    [[ -f "$dir/cloudflare.config.ts" ]] && { printf '%s' "$dir/cloudflare.config.ts"; return 0; }
    [[ "$dir" == / || -z "$dir" ]] && return 1
    dir=${dir%/*}; [[ -z "$dir" ]] && dir=/
  done
}

# The account cf saved for a project on an earlier command: cloudflare-account
# [-<profile>].json under the nearest node_modules/.cache/cloudflare/, or under
# .cloudflare/cache/ in the run directory. Prints "file<TAB>account id" lines.
cf_saved_accounts() {
  local dir="$1" d f v
  d="$dir"
  while :; do
    if [[ -d "$d/node_modules" ]]; then
      for f in "$d"/node_modules/.cache/cloudflare/cloudflare-account*.json; do
        [[ -f "$f" ]] || continue
        v=$(grep -o '[0-9a-f]\{32\}' "$f" | head -1)
        printf '%s\t%s\n' "$f" "${v:-unreadable}"
      done
      break
    fi
    [[ "$d" == / || -z "$d" ]] && break
    d=${d%/*}; [[ -z "$d" ]] && d=/
  done
  for f in "$dir"/.cloudflare/cache/cloudflare-account*.json; do
    [[ -f "$f" ]] || continue
    v=$(grep -o '[0-9a-f]\{32\}' "$f" | head -1)
    printf '%s\t%s\n' "$f" "${v:-unreadable}"
  done
}
