#!/usr/bin/env bash
# Reading a `cf` (Cloudflare CLI) command line. Sourced by
# scripts/guard-cloudflare.sh.
#
# cf maps almost every command to one REST API request. lib/cf-commands.tsv,
# generated by scripts/gen-cf-table.py from cf's own manifest, records that
# request (method and path template), the positional arguments, which options
# take a value, and which carry a credential. The guard fills the path template
# from the command line and checks the result exactly like a curl call.

CF_TABLE="${CF_TABLE:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" 2>/dev/null && pwd -P)/cf-commands.tsv}"

# Global options of every cf command (from `cf <any> --help`).
CF_GLOBAL_VAL=" -z --zone --profile -m --mode --persist-to "

# cf_lookup <path> — sets CF_ROW to the table line for an exact command path.
cf_lookup() {
  CF_ROW=$(CF_P="$1" awk -F '\t' '$1 == ENVIRON["CF_P"] { print; exit }' "$CF_TABLE" 2>/dev/null)
  [[ -n "$CF_ROW" ]]
}

# parse_cf — reads SH_WORDS from SH_START + 1. Sets:
#   CF_CMD CF_KIND CF_METHOD CF_API CF_CATEGORY   the command and its table row
#   CF_ARGN[] CF_ARGV[]       positional argument names and the values given
#   CF_OPTN[] CF_OPTV[]       options given (name without dashes, last value)
#   CF_ZONE CF_DRYRUN CF_HELP CF_BODY CF_DUP CF_SECRET_LIT CF_FIRSTPOS
parse_cf() {
  CF_CMD=""; CF_KIND=""; CF_METHOD=""; CF_API=""; CF_CATEGORY=""; CF_ARGN=(); CF_ARGV=()
  CF_OPTN=(); CF_OPTV=(); CF_ZONE=""; CF_DRYRUN=0; CF_HELP=0; CF_BODY=""; CF_DUP=""
  CF_SECRET_LIT=""; CF_FIRSTPOS=""
  local n=${#SH_WORDS[@]} j=$((SH_START + 1)) t f val b bv k p i
  local -a lead=()
  # The command path: the leading words, skipping global options.
  while (( j < n )); do
    t=${SH_WORDS[j]}
    if [[ "$CF_GLOBAL_VAL" == *" $t "* ]]; then j=$((j + 2)); continue; fi
    [[ "$t" == -* ]] && break
    lead[${#lead[@]}]="$t"
    j=$((j + 1))
  done
  CF_FIRSTPOS="${lead[0]:-}"
  k=${#lead[@]}; (( k > 5 )) && k=5
  while (( k > 0 )); do
    p="${lead[0]}"; i=1
    while (( i < k )); do p="$p ${lead[i]}"; i=$((i + 1)); done
    if cf_lookup "$p"; then CF_CMD="$p"; break; fi
    k=$((k - 1))
  done
  [[ -n "$CF_CMD" ]] || { CF_LEAD=$k; return 0; }
  local kind method api args vals secrets cat
  IFS=$'\t' read -r _ kind method api args vals secrets cat <<< "$CF_ROW"
  CF_KIND=$kind; CF_METHOD=$method; CF_API=$api; CF_CATEGORY=$cat
  local -a argn=()
  [[ "$args" == - ]] || IFS=, read -r -a argn <<< "$args"
  vals=",${vals},"; secrets=",${secrets},"

  # Everything after the command path, in order.
  local skip=$k pos=0
  j=$((SH_START + 1))
  while (( j < n )); do
    t=${SH_WORDS[j]}
    if [[ "$t" == -- ]]; then j=$((j + 1)); continue; fi
    if [[ "$t" == -?* ]]; then
      f=${t%%=*}
      # Booleans the guard acts on, read the way yargs reads them.
      b=""; bv=1
      case "$f" in
        -h|--help) b=help ;; -v|--version) b=help ;; --dry-run) b=dry ;;
        --no-dry-run) b=dry; bv=0 ;; --no-help) b=help; bv=0 ;;
      esac
      if [[ -n "$b" ]]; then
        if [[ "$t" == *=* ]]; then [[ "${t#*=}" == false ]] && bv=0
        elif [[ "$f" != --no-* ]] && [[ "${SH_WORDS[j+1]:-}" == true || "${SH_WORDS[j+1]:-}" == false ]]; then
          [[ "${SH_WORDS[j+1]}" == false ]] && bv=0; j=$((j + 1))
        fi
        case "$b" in help) CF_HELP=$bv ;; dry) CF_DRYRUN=$bv ;; esac
        j=$((j + 1)); continue
      fi
      val=""
      local name=${f#--}; name=${name#-}
      if [[ "$t" == *=* ]]; then val=${t#*=}
      elif [[ "$CF_GLOBAL_VAL" == *" $f "* || ( "$f" == --* && "$vals" == *",$name,"* ) ]]; then
        val="${SH_WORDS[j+1]:-}"; j=$((j + 1))
      else
        j=$((j + 1)); continue                      # a boolean option
      fi
      case "$f" in
        -z|--zone) CF_ZONE="$val" ;;
        --body)    CF_BODY="$val" ;;
      esac
      if [[ "$secrets" == *",$name,"* ]] && is_literal "$val" && [[ -z "$CF_SECRET_LIT" ]]; then CF_SECRET_LIT="--$name"; fi
      # An option given twice: the guard cannot know which value cf uses.
      for i in ${CF_OPTN[@]+"${!CF_OPTN[@]}"}; do
        [[ "${CF_OPTN[i]}" == "$name" && "${CF_OPTV[i]}" != "$val" ]] && CF_DUP="--$name"
      done
      CF_OPTN[${#CF_OPTN[@]}]="$name"; CF_OPTV[${#CF_OPTV[@]}]="$val"
      j=$((j + 1)); continue
    fi
    if (( skip > 0 )); then skip=$((skip - 1)); j=$((j + 1)); continue; fi
    CF_ARGN[${#CF_ARGN[@]}]="${argn[pos]:-extra}"; CF_ARGV[${#CF_ARGV[@]}]="$t"
    pos=$((pos + 1)); j=$((j + 1))
  done
  return 0
}

# cf_opt <name> — sets CF_V to the option's value; fails when not given.
cf_opt() {
  local i
  CF_V=""
  for i in ${CF_OPTN[@]+"${!CF_OPTN[@]}"}; do
    [[ "${CF_OPTN[i]}" == "$1" ]] && { CF_V="${CF_OPTV[i]}"; return 0; }
  done
  return 1
}

# cf_param <path param> — sets CF_V to the value the command gives a path
# parameter: the positional or option of the same name (dashes for underscores),
# or a known alias (`workers deployments create --worker` names the script).
cf_param() {
  local p="$1" d i
  d=${p//_/-}
  CF_V=""
  for i in ${CF_ARGN[@]+"${!CF_ARGN[@]}"}; do
    [[ "${CF_ARGN[i]}" == "$d" || "${CF_ARGN[i]}" == "$p" ]] && { CF_V="${CF_ARGV[i]}"; return 0; }
  done
  cf_opt "$d" && return 0
  cf_opt "$p" && return 0
  case "$p" in
    script_name) cf_opt worker && return 0; cf_opt script && return 0 ;;
  esac
  return 1
}

# The name a create command gives the new resource, from its options. Sets CF_V
# and CF_NAME_OPT; fails when the command names it nowhere the guard can read.
CF_NAME_OPTS="name title queue-name bucket-name script-name database-name index-name project-name namespace-name tunnel-name"
cf_create_name() {
  local o
  CF_NAME_OPT=""
  for o in $CF_NAME_OPTS; do
    if cf_opt "$o"; then CF_NAME_OPT="--$o"; return 0; fi
  done
  return 1
}

# The nearest cloudflare.config.ts from a directory upward, or fail.
cf_config_ts() {
  local dir="$1"
  while :; do
    [[ -f "$dir/cloudflare.config.ts" ]] && { printf '%s' "$dir/cloudflare.config.ts"; return 0; }
    [[ "$dir" == / || -z "$dir" ]] && return 1
    dir=${dir%/*}; [[ -z "$dir" ]] && dir=/
  done
}

# The account cf saved for a project on an earlier command: cloudflare-account
# [-<profile>].json under the nearest node_modules/.cache/cloudflare/, or under
# .cloudflare/cache/ in the run directory. Prints "file<TAB>account id" lines.
cf_saved_accounts() {
  local dir="$1" d f v
  d="$dir"
  while :; do
    if [[ -d "$d/node_modules" ]]; then
      for f in "$d"/node_modules/.cache/cloudflare/cloudflare-account*.json; do
        [[ -f "$f" ]] || continue
        v=$(grep -o '[0-9a-f]\{32\}' "$f" | head -1)
        printf '%s\t%s\n' "$f" "${v:-unreadable}"
      done
      break
    fi
    [[ "$d" == / || -z "$d" ]] && break
    d=${d%/*}; [[ -z "$d" ]] && d=/
  done
  for f in "$dir"/.cloudflare/cache/cloudflare-account*.json; do
    [[ -f "$f" ]] || continue
    v=$(grep -o '[0-9a-f]\{32\}' "$f" | head -1)
    printf '%s\t%s\n' "$f" "${v:-unreadable}"
  done
}
